config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get "dashboards/show"
  end
  devise_for :users

  authenticate :user, ->(user) { user.admin? } do
    mount Blazer::Engine, at: "blazer"
  end

  namespace :admin do
    resource :dashboard, only: [:show]
  end

  resources :users do
    member do
      post "save_plan", to: "saved_plans#create", as: "save_plan"
      delete "remove_saved_plan", to: "saved_plans#destroy", as: "remove_saved_plan"
    end
  end

  resources :plans, only: %i[index show new create edit update destroy]

  resources :saved_plans, only: %i[show create destroy]

  resources :course_requirements

  resources :transferable_courses

  resources :courses do
    resources :transferable_courses
  end

  resources :degree_requirements do
    resources :course_requirements, only: [:create]
  end

  resources :schools do
    resources :degrees, only: [:create]
    resources :courses, only: [:create]
    resources :terms, except: [:show]
    post "scrape_courses", on: :member
  end

  resources :terms

  resources :degrees do
    resources :degree_requirements, only: [:create]
    post "generate_cheapest_plan",
         to: "admin_cheapest_plan#create",
         as: "generate_cheapest_plan",
         on: :member
  end

  get "/plan_page", to: "pages#plan_page", as: "plan_page"

  get "/show_plan", to: "pages#show_plan", as: "show_plan"
  get "save_plan_prompt", to: "users#save_plan_prompt", as: "prompt_save_plan"
  post "/generate_plan", to: "pages#generate_plan", as: "generate_plan"

  root "pages#home"
end

app/controllers/transferable_courses_controller.rb
class TransferableCoursesController < ApplicationController
  before_action { authorize(@transferable_course || TransferableCourse) }
  before_action :set_transferable_course, only: %i[show edit update destroy]

  def index
    @transferable_courses = TransferableCourse.all
  end

  def show
    @transferable_to_courses = @transferable_course.from_course.transferable_to_courses
    @transferable_from_courses = @transferable_course.from_course.transferable_from_courses
    @course = @transferable_course.to_course
  end

  def new
    @transferable_course = TransferableCourse.new
  end

  def edit
    @other_courses = Course.where.not(id: @transferable_course.to_course_id)
  end

  def create
    @transferable_course = TransferableCourse.create_with_associations(transferable_course_params)
    @course = Course.find(transferable_course_params[:to_course_id])
    @other_courses = Course.for_transfer_form(@course.id)

    respond_to do |format|
      if @transferable_course.persisted?
        @saved_course = @transferable_course
        @transferable_course = TransferableCourse.initialize_for_course(@course.id)
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @transferable_course.update(transferable_course_params)
        format.html do
          redirect_to transferable_course_url(@transferable_course),
                      notice: "Transferable course was successfully updated."
        end
        format.json { render :show, status: :ok, location: @transferable_course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transferable_course.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    source_course_id = @transferable_course.to_course_id
    @transferable_course.destroy!

    respond_to do |format|
      format.html do
        redirect_to course_path(source_course_id),
                    notice: "Transfer relationship was successfully removed."
      end
      format.json { head :no_content }
    end
  end

  private

  def set_transferable_course
    @transferable_course = TransferableCourse.with_associated_courses.find(params[:id])
  end

  def transferable_course_params
    params.require(:transferable_course).permit(
      :from_course_id,
      :to_course_id,
      :degree_requirement_id
    )
  end
end

app/views/transferable_courses/_form.html.erb
<%= form_with(model: @transferable_course, local: false, html: { id: "new-transferable-course-form" }) do |form| %>
  <%= form_errors(@transferable_course) %>
  <%= form.hidden_field :to_course_id, value: @transferable_course.to_course_id %>

  <div class="mb-4 row justify-content-center">
    <div class="col-md-10">
      <%= form.label :from_course_id, "Transferable Course", class: "form-label fs-4 mb-2" %>
      <%= form.collection_select :from_course_id,
                             @other_courses,
                             :id,
                             :name_with_school,
                             { prompt: "Select a course" },
                             class: "form-select fs-4" %>
    </div>
  </div>

  <div class="row justify-content-center">
    <div class="col-md-10 text-center">
      <%= form.submit class: "btn custom-btn-2 fs-4" %>
    </div>
  </div>
<% end %>

app/views/transferable_courses/_transferable_course.html.erb
<div id="<%= dom_id transferable_course %>">
  <p>
    <strong>From course:</strong>
    <%= transferable_course.from_course_id %>
  </p>

  <p>
    <strong>To course:</strong>
    <%= transferable_course.to_course_id %>
  </p>

</div>

app/views/transferable_courses/_transferable_course_list_item.html.erb
<li
  id="transferable_course_<%= transferable_course.id %>"
  class="list-group-item"
>
  <%= link_to transferable_course_path(transferable_course, source_course_id: transferable_course.to_course_id), class: "fs-4 text-decoration-none" do %>
    <%= transferable_course.formatted_relation %>
  <% end %>
</li>

app/views/transferable_courses/create.turbo_stream.erb
<%= turbo_stream.append "transferable-courses-list" do %>
  <%= render partial: 'transferable_courses/transferable_course_list_item', locals: { transferable_course: @saved_course } %>
<% end %>

<%= turbo_stream.replace "new-transferable-course-form" do %>
  <%= render "form", transferable_course: @transferable_course %>
<% end %>

<%= turbo_stream.update "alert-container" do %>
  <p class="notice fs-4">Transferable course was successfully created.</p>
<% end %>

app/views/transferable_courses/edit.html.erb
<h1>Editing transferable course</h1>

<%= render "form", transferable_course: @transferable_course %>

<br>

<div>
  <%= link_to "Show this transferable course", @transferable_course %>
  |
  <%= link_to "Back to transferable courses", transferable_courses_path %>
</div>

app/views/transferable_courses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Transferable courses</h1>

<div id="transferable_courses">
  <% @transferable_courses.each do |transferable_course| %>
    <%= render transferable_course %>
    <p>
      <%= link_to "Show this transferable course", transferable_course %>
    </p>
  <% end %>
</div>

<%= link_to "New transferable course", new_transferable_course_path %>

app/views/transferable_courses/new.html.erb
<h1>New transferable course</h1>

<%= render "form", transferable_course: @transferable_course %>

<br>

<div>
  <%= link_to "Back to transferable courses", transferable_courses_path %>
</div>

app/views/transferable_courses/show.html.erb
<div class="container mt-5">
  <div class="card shadow custom-card">
    <div class="card-body">
      <p class="text-success fs-4"><%= notice %></p>

      <h2 class="mb-4">Course Transfer Details</h2>

      <div class="mb-4">
        <h4>From:</h4>
        <p class="fs-5">
          <%= link_to @transferable_course.from_course_details,
          course_path(@transferable_course.from_course) %>
        </p>

        <h4>To:</h4>
        <p class="fs-5">
          <%= link_to @transferable_course.to_course_details,
          course_path(@transferable_course.to_course) %>
        </p>
      </div>

      <div class="mt-4">
        <%= button_to "Delete Transfer Relationship",
        transferable_course_path(@transferable_course),
        method: :delete,
        class: "btn custom-btn fs-4 me-2",
        data: {
          confirm: "Are you sure you want to delete this transfer relationship?",
        } %>
        <%= link_to "Back to Course",
        course_path(params[:source_course_id] || @transferable_course.to_course),
        class: "btn custom-btn fs-4" %>
      </div>
    </div>
  </div>
</div>