config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get "dashboards/show"
  end
  devise_for :users

  authenticate :user, ->(user) { user.admin? } do
    mount Blazer::Engine, at: "blazer"
  end

  namespace :admin do
    resource :dashboard, only: [:show]
  end

  resources :users do
    member do
      post "save_plan", to: "saved_plans#create", as: "save_plan"
      delete "remove_saved_plan", to: "saved_plans#destroy", as: "remove_saved_plan"
    end
  end

  resources :plans, only: %i[index show new create edit update destroy]

  resources :saved_plans, only: %i[show create destroy]

  resources :course_requirements

  resources :transferable_courses

  resources :courses do
    resources :transferable_courses
  end

  resources :degree_requirements do
    resources :course_requirements, only: [:create]
  end

  resources :schools do
    resources :degrees, only: [:create]
    resources :courses, only: [:create]
    resources :terms, except: [:show]
    post "scrape_courses", on: :member
  end

  resources :terms

  resources :degrees do
    resources :degree_requirements, only: [:create]
    post "generate_cheapest_plan",
         to: "admin_cheapest_plan#create",
         as: "generate_cheapest_plan",
         on: :member
  end

  get "/plan_page", to: "pages#plan_page", as: "plan_page"

  get "/show_plan", to: "pages#show_plan", as: "show_plan"
  get "save_plan_prompt", to: "users#save_plan_prompt", as: "prompt_save_plan"
  post "/generate_plan", to: "pages#generate_plan", as: "generate_plan"

  root "pages#home"
end

app/views/layouts/shared/_alerts.html.erb
<p class="notice fs-4"><%= notice %></p>
<p class="alert fs-4"><%= alert %></p>

app/views/layouts/shared/_head.html.erb
<%= favicon_link_tag "favicon.png", type: "image/png" %>
<link
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
  rel="stylesheet"
  integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
  crossorigin="anonymous"
>
<meta name="viewport" content="width=device-width,initial-scale=1">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link
  href="https://fonts.googleapis.com/css2?family=Darker+Grotesque:wght@300..900&display=swap"
  rel="stylesheet"
>
<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"
>
<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<%= javascript_importmap_tags %>

app/views/layouts/shared/_navigation.html.erb
<div id="nav">
  <nav class="navbar navbar-expand-lg custom-navbar">
    <div class="container-fluid">
      <a class="navbar-brand fs-3" href="<%= root_path %>">
        <%= image_tag "favicon.png", alt: "Logo", width: "30", height: "24" %>
        Discount Degree
      </a>
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <%= image_tag "hamburger.png", alt: "Menu", width: "30", height: "24" %>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto fs-4">
          <% if user_signed_in? %>
            <% if policy(School).index? %>
              <li class="nav-item">
                <%= link_to "Dashboard", admin_dashboard_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Schools", schools_path, class: "nav-link" %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "Profile", user_path(current_user), class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Plans", plans_path, class: "nav-link" %>
              </li>
            <% end %>
            <li class="nav-item">
              <%= link_to "Sign out",
              destroy_user_session_path,
              class: "nav-link",
              data: {
                turbo_method: :delete,
              } %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</div>