config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get "dashboards/show"
  end
  devise_for :users

  authenticate :user, ->(user) { user.admin? } do
    mount Blazer::Engine, at: "blazer"
  end

  namespace :admin do
    resource :dashboard, only: [:show]
  end

  resources :users do
    member do
      post "save_plan", to: "saved_plans#create", as: "save_plan"
      delete "remove_saved_plan", to: "saved_plans#destroy", as: "remove_saved_plan"
    end
  end

  resources :plans, only: %i[index show new create edit update destroy]

  resources :saved_plans, only: %i[show create destroy]

  resources :course_requirements

  resources :transferable_courses

  resources :courses do
    resources :transferable_courses
  end

  resources :degree_requirements do
    resources :course_requirements, only: [:create]
  end

  resources :schools do
    resources :degrees, only: [:create]
    resources :courses, only: [:create]
    resources :terms, except: [:show]
    post "scrape_courses", on: :member
  end

  resources :terms

  resources :degrees do
    resources :degree_requirements, only: [:create]
    post "generate_cheapest_plan",
         to: "admin_cheapest_plan#create",
         as: "generate_cheapest_plan",
         on: :member
  end

  get "/plan_page", to: "pages#plan_page", as: "plan_page"

  get "/show_plan", to: "pages#show_plan", as: "show_plan"
  get "save_plan_prompt", to: "users#save_plan_prompt", as: "prompt_save_plan"
  post "/generate_plan", to: "pages#generate_plan", as: "generate_plan"

  root "pages#home"
end

app/models/degree.rb
# == Schema Information
#
# Table name: degrees
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  school_id  :bigint           not null
#
# Indexes
#
#  index_degrees_on_school_id  (school_id)
#
# Foreign Keys
#
#  fk_rails_...  (school_id => schools.id)
#
class Degree < ApplicationRecord
  has_many :degree_requirements,
           class_name: "DegreeRequirement",
           foreign_key: "degree_id",
           dependent: :destroy
  belongs_to :school, required: true, class_name: "School", foreign_key: "school_id"
  has_many :plans, dependent: :destroy

  def self.ransackable_attributes(auth_object = nil)
    ["name"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["school"]
  end
end

app/controllers/degrees_controller.rb
class DegreesController < ApplicationController
  before_action { authorize(@degree || Degree) }
  before_action :set_degree, only: %i[show edit update destroy]
  before_action :set_school, only: [:create]

  def index
    @degrees = Degree.includes(:school).all
  end

  def show
    @plans = @degree.plans.order(created_at: :desc)
  end

  def new
    @degree = Degree.new
  end

  def edit
  end

  def create
    @degree = @school.degrees.build(degree_params)

    respond_to do |format|
      if @degree.save
        format.html do
          redirect_to school_path(@school, section: "degrees"),
                      notice: "Degree was successfully created."
        end
        format.json { render :show, status: :created, location: @degree }
      else
        format.html do
          redirect_to school_path(@school, section: "degrees"), status: :unprocessable_entity
        end
        format.json { render json: @degree.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @degree.update(degree_params)
        format.html { redirect_to degree_url(@degree), notice: "Degree was successfully updated." }
        format.json { render :show, status: :ok, location: @degree }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @degree.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    school = @degree.school
    @degree.destroy!
    redirect_to school_path(school, section: "degrees"),
                notice: "Degree was successfully destroyed."
  end

  private

  def set_degree
    @degree = Degree.find(params[:id])
  end

  def set_school
    @school = School.find(params[:school_id])
  end

  def degree_params
    params.require(:degree).permit(:name, :school_id)
  end
end

app/views/degrees/_degree.html.erb
<div id="<%= dom_id degree %>">
  <p>
    <strong>Name:</strong>
    <%= degree.name %>
  </p>

  <p>
    <strong>School:</strong>
    <%= degree.school.name %>
  </p>

</div>

app/views/degrees/_degree_list_item.html.erb
<li id="degree_<%= degree.id %>">
  <%= link_to degree.name, degree_path(degree) %>
</li>

app/views/degrees/_form.html.erb
<div class="container pt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card shadow custom-card">
        <div class="card-body">
          <h2 class="card-title mb-4 fs-3">Add New Degree</h2>

          <%= form_with(model: [@school, @degree], local: true, html: { id: "new-degree-form" }) do |form| %>
            <%= form_errors(@degree) %>

            <div class="mb-4 row justify-content-center">
              <div class="col-md-10">
                <%= form.label :name, "Degree Name", class: "form-label fs-4 mb-2" %>
                <%= form.text_field :name, class: "form-control fs-4" %>
              </div>
            </div>

            <div class="row justify-content-center">
              <div class="col-md-10 text-center">
                <%= form.submit "Add Degree", class: "btn custom-btn-2 fs-4" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/degrees/create.js.erb
document.getElementById("degrees-list").insertAdjacentHTML(
  "beforeend",
  "<%= j render(partial: 'degrees/degree_list_item', locals: { degree: @degree }) %>"
);

document.getElementById("new-degree-form").reset();

app/views/degrees/edit.html.erb
<h1>Editing degree</h1>

<%= render "form", degree: @degree %>

<br>

<div>
  <%= link_to "Show this degree", @degree %>
  |
  <%= link_to "Back to degrees", degrees_path %>
</div>

app/views/degrees/index.html.erb
<div class="admin-container">
  <h1 class="admin-header">Degrees</h1>

  <div class="row">
    <% @degrees.each do |degree| %>
      <div class="col-md-4 mb-4">
        <div class="card shadow custom-card">
          <div class="card-body">
            <%= render degree %>
            <div class="admin-actions mt-3">
              <%= link_to "Show", degree, class: "btn custom-btn-2" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="text-center mt-4">
    <%= link_to "New Degree", new_degree_path, class: "btn custom-btn-2 fs-4" %>
  </div>
</div>

app/views/degrees/new.html.erb
<h1>New degree</h1>

<%= render "form", degree: @degree %>

<br>

<div>
  <%= link_to "Back to degrees", degrees_path %>
</div>

app/views/degrees/show.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-10">
      <div class="card shadow custom-card">
        <div class="card-body">
          <div>
            <%= render @degree %>
          </div>
          <div class="d-flex justify-content-between mt-4">
            <%= link_to "Edit this degree",
            edit_degree_path(@degree),
            class: "btn custom-btn fs-4" %>
            <%= button_to "Destroy this degree",
            degree_path(@degree),
            method: :delete,
            class: "btn custom-btn fs-4",
            data: {
              turbo: false,
            } %>
            <%= link_to "Back to school",
            school_path(@degree.school, section: "degrees"),
            class: "btn custom-btn fs-4" %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="mt-5">
    <h3 class="fs-3">Add a Requirement</h3>
    <div class="card shadow custom-card mt-3">
      <div class="card-body">
        <%= form_with(model: [@degree, DegreeRequirement.new(degree: @degree)], local: true) do |form| %>
          <% if form.object.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(form.object.errors.count, "error") %>
                prohibited this requirement from being saved:</h2>

              <ul>
                <% form.object.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="mb-4 row justify-content-center">
            <div class="col-md-10">
              <%= form.label :name, "Requirement Name", class: "form-label fs-4 mb-2" %>
              <%= form.text_field :name, class: "form-control fs-4" %>
            </div>
          </div>

          <div class="mb-4 row justify-content-center">
            <div class="col-md-10">
              <%= form.label :credit_hour_amount,
                         "Credit Hour Amount",
                         class: "form-label fs-4 mb-2" %>
              <%= form.number_field :credit_hour_amount, class: "form-control fs-4" %>
            </div>
          </div>

          <div class="row justify-content-center">
            <div class="col-md-10 text-center">
              <%= form.submit "Add Requirement",
                          class: "btn custom-btn-2 fs-4",
                          data: {
                            disable_with: "Adding...",
                          } %>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <div class="mt-5">
      <h3 class="fs-3">Requirements</h3>
      <% if @degree.degree_requirements.where.not(id: nil).any? %>
        <ul id="degree-requirements-list" class="list-unstyled mt-4">
          <% @degree.degree_requirements.where.not(id: nil).each do |requirement| %>
            <%= render "degree_requirements/degree_requirement_list_item",
            degree: @degree,
            degree_requirement: requirement %>
          <% end %>
        </ul>
      <% else %>
        <p>No requirements have been added yet.</p>
      <% end %>
    </div>
  </div>

  <h2 class="mt-5">Find Cheapest Plan</h2>
  <div class="card shadow custom-card mt-3">
    <div class="card-body">
      <%= form_with url: generate_cheapest_plan_degree_path(@degree), local: true, method: :post, scope: :plan do |form| %>
        <% if flash[:alert] %>
          <div class="alert alert-danger"><%= flash[:alert] %></div>
        <% end %>

        <div class="form-group">
          <%= form.label :starting_school_id, "Select Starting School" %>
          <%= form.select :starting_school_id,
                      options_from_collection_for_select(
                        School.where(school_type: "community_college"),
                        :id,
                        :name,
                      ),
                      { prompt: "Select Starting School" },
                      class: "form-select",
                      required: true %>
        </div>

        <div class="actions mt-3">
          <%= form.submit "Generate Cheapest Plan", class: "btn custom-btn btn-block fs-4" %>
        </div>
      <% end %>
    </div>
  </div>

  <h2 class="mt-5">Generated Plan</h2>
  <div class="card shadow custom-card mt-3">
    <div class="card-body">
      <% if @plans.any? %>
        <%= render @plans %>
      <% else %>
        <p class="text-muted">No plans generated yet.</p>
      <% end %>
    </div>
  </div>
</div>